# Site settings
title: 개발자 정재욱입니다
email: dnrlwo11@gmail.com
url: https://dnrlwo.github.io
description: "다양한 것을 이해하고, 다양한 것을 경험하며, 다양한 것을 나눌 수 있는 개발을 하고 싶은 정재욱입니다."
keywords: "Dreamer, Front-End Engineer"
skills: "Full-stack Engineer"
meta_author: 재욱 정

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: woogie

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 117070 #18bc9c
  primary-rgb: "0, 80, 80" #"24, 288, 156"
  secondary: 696969 #2c3e50
  secondary-rgb: "105, 105, 105"
  secondary-dark: 525252 #233140

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/dnrlwo
  - title: facebook
    url: https://www.facebook.com/jung.jaeuk.9
  - title: instagram
    url: https://www.instagram.com/woogi_j_/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: ""

# Build settings
markdown: kramdown
permalink: pretty
